package org.sparcs.soap.nearbyTests

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertThrows
import org.junit.Test
import org.sparcs.soap.app.domain.nearby.BeaconUuid
import org.sparcs.soap.app.domain.nearby.NearbyCrypto
import org.sparcs.soap.app.domain.nearby.NearbyJson
import org.sparcs.soap.app.domain.nearby.NearbyMessageBody
import org.sparcs.soap.app.domain.nearby.NearbyMessageType
import org.sparcs.soap.app.domain.nearby.NearbySession
import org.sparcs.soap.app.domain.nearby.PresenceCard

/**
 * Reproduces every value in the shared `nearby-test-vectors.json` (generated by
 * sparcsapp-back's reference implementation, copied byte for byte), so Android
 * stays interoperable with iOS.
 */
class NearbyCryptoTest {

    private val vectors: JsonObject = Json.parseToJsonElement(
        javaClass.classLoader!!.getResource("nearby-test-vectors.json")!!.readText()
    ).jsonObject

    private fun JsonObject.str(key: String) = getValue(key).jsonPrimitive.content
    private fun JsonObject.hex(key: String) = NearbyCrypto.fromHex(str(key))
    private fun section(key: String) = vectors.getValue(key).jsonObject

    private fun session(party: String): NearbySession {
        val values = section(party)
        return NearbySession(
            NearbyCrypto.keyPairFromRawPrivateKey(values.hex("privateKeyRaw")),
            values.hex("ownerSecret")
        )
    }

    @Test
    fun `session values match for both parties`() {
        for (party in listOf("a", "b")) {
            val values = section(party)
            val session = session(party)
            assertEquals(values.str("publicKeyX963"), NearbyCrypto.hex(session.pubX963))
            assertEquals(values.str("token"), session.tokenHex)
            assertEquals(values.str("beaconUuid"), session.beaconUuid)
            assertEquals(values.str("lookupId"), NearbyCrypto.hex(session.lookupId))
            assertEquals(values.str("presenceKey"), NearbyCrypto.hex(session.presenceKey))
            assertEquals(values.str("ownerSecretBase64Url"), NearbyCrypto.base64Url(session.ownerSecret))
        }
    }

    @Test
    fun `presence seals and opens`() {
        val a = session("a")
        val presence = section("presence")
        val aad = NearbyCrypto.PRESENCE_INFO + a.lookupId
        assertEquals(presence.str("aad"), NearbyCrypto.hex(aad))

        val sealed = NearbyCrypto.seal(
            a.presenceKey,
            presence.str("plaintextUtf8").toByteArray(),
            aad,
            nonce = presence.hex("nonce")
        )
        assertEquals(presence.str("sealed"), NearbyCrypto.hex(sealed))
        assertEquals(presence.str("sealedBase64Url"), NearbyCrypto.base64Url(sealed))

        val card = NearbyJson.json.decodeFromString(
            PresenceCard.serializer(),
            String(NearbyCrypto.open(a.presenceKey, sealed, aad))
        )
        assertEquals("홍길동", card.name)
        assertEquals("ios", card.platform)
        assertArrayEquals(a.token, NearbyCrypto.token(NearbyCrypto.fromBase64Url(card.pub)))
    }

    @Test
    fun `header seals with the recipient's presence key`() {
        val a = session("a")
        val b = session("b")
        val header = section("header")
        assertEquals(header.str("key"), NearbyCrypto.hex(b.presenceKey))
        val aad = NearbyCrypto.HEADER_AAD + b.lookupId
        assertEquals(header.str("aad"), NearbyCrypto.hex(aad))
        val sealed = NearbyCrypto.seal(b.presenceKey, a.token, aad, nonce = header.hex("nonce"))
        assertEquals(header.str("sealed"), NearbyCrypto.hex(sealed))
        assertArrayEquals(a.token, NearbyCrypto.open(b.presenceKey, sealed, aad))
    }

    @Test
    fun `pair key agrees in both directions`() {
        val a = session("a")
        val b = session("b")
        val pair = section("pair")
        assertEquals(
            pair.str("sharedSecret"),
            NearbyCrypto.hex(NearbyCrypto.sharedSecret(a.keyPair.private, b.keyPair.public))
        )
        assertEquals(
            pair.str("sharedSecret"),
            NearbyCrypto.hex(NearbyCrypto.sharedSecret(b.keyPair.private, NearbyCrypto.publicKeyFromX963(a.pubX963)))
        )
        assertEquals(pair.str("pairKey"), NearbyCrypto.hex(NearbyCrypto.pairKey(a.keyPair.private, b.pubX963, a.token, b.token)))
        assertEquals(pair.str("pairKey"), NearbyCrypto.hex(NearbyCrypto.pairKey(b.keyPair.private, a.pubX963, b.token, a.token)))
    }

    @Test
    fun `body seals with the pair key`() {
        val a = session("a")
        val b = session("b")
        val body = section("body")
        val pairKey = NearbyCrypto.fromHex(section("pair").str("pairKey"))
        val aad = NearbyCrypto.BODY_AAD + b.lookupId + a.token
        assertEquals(body.str("aad"), NearbyCrypto.hex(aad))
        val sealed = NearbyCrypto.seal(pairKey, body.str("plaintextUtf8").toByteArray(), aad, nonce = body.hex("nonce"))
        assertEquals(body.str("sealed"), NearbyCrypto.hex(sealed))

        val decoded = NearbyJson.json.decodeFromString(
            NearbyMessageBody.serializer(),
            String(NearbyCrypto.open(pairKey, sealed, aad))
        )
        assertEquals(NearbyMessageType.Accept, decoded.type)
        assertEquals("ACD347", decoded.friendCode)
        assertEquals(1790590000123, decoded.sentAt)
    }

    @Test
    fun `tampered ciphertext, wrong key or wrong aad fail to open`() {
        val a = session("a")
        val presence = section("presence")
        val aad = presence.hex("aad")
        val sealed = presence.hex("sealed")

        val flipped = sealed.copyOf().also { it[20] = (it[20].toInt() xor 1).toByte() }
        assertThrows(Exception::class.java) { NearbyCrypto.open(a.presenceKey, flipped, aad) }
        assertThrows(Exception::class.java) { NearbyCrypto.open(session("b").presenceKey, sealed, aad) }
        assertThrows(Exception::class.java) { NearbyCrypto.open(a.presenceKey, sealed, aad + byteArrayOf(0)) }
        assertThrows(Exception::class.java) { NearbyCrypto.open(a.presenceKey, sealed.copyOf(20), aad) }
    }

    @Test
    fun `a card for another key fails the commitment check`() {
        // The relay could swap in B's card under A's lookup ID; the token says otherwise.
        val a = session("a")
        val b = session("b")
        assertFalse(NearbyCrypto.token(b.pubX963).contentEquals(a.token))
    }

    @Test
    fun `x963 encoding round-trips random keys with short coordinates`() {
        repeat(64) {
            val keyPair = NearbyCrypto.generateKeyPair()
            val encoded = NearbyCrypto.x963(keyPair.public)
            assertEquals(65, encoded.size)
            assertEquals(0x04.toByte(), encoded[0])
            assertArrayEquals(encoded, NearbyCrypto.x963(NearbyCrypto.publicKeyFromX963(encoded)))
        }
    }

    @Test
    fun `beacon uuid round-trips and rejects other uuids`() {
        val a = session("a")
        assertArrayEquals(a.token, BeaconUuid.token(a.beaconUuid))
        assertArrayEquals(a.token, BeaconUuid.token(a.beaconUuid.uppercase()))
        section("beacon").getValue("rejected").jsonArray.forEach {
            assertNull(BeaconUuid.token(it.jsonPrimitive.content))
        }
        assertNull(BeaconUuid.token("b0dd1e01-zzzz-0000-0000-000000000000"))
    }

    @Test
    fun `names are capped at 64 utf8 bytes on a character boundary`() {
        val name = "홍".repeat(30) // 3 bytes each
        val truncated = NearbyJson.truncatedName(name)
        assertEquals(21, truncated.length)
        assertEquals("Short", NearbyJson.truncatedName("Short"))
    }

    @Test
    fun `unknown message types decode as null so they can be ignored`() {
        val body = NearbyJson.json.decodeFromString(
            NearbyMessageBody.serializer(),
            """{"v":1,"type":"wave","msgId":"x","sentAt":1,"extra":true}"""
        )
        assertNull(body.type)
    }
}
